### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by andyli** [earthly/actions-setup#10]
I'm seeing this warning in GitHub Actions

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: earthly/actions-setup

**Comment by kevinschoonover** [comment]
The master branch is currently on 16 https://github.com/earthly/actions-setup/blob/79c1a7ec26c371d868724182ec98d7434b18521f/action.yml#L12-L14. Try pinning the commit to something like suggested in #6 and see if that fixes it

**Comment by andyli** [comment]
With `earthly/actions-setup@79c1a7ec26c371d868724182ec98d7434b18521f` the warning about node12 disappeared.

However, there are 3 new warnings that doesn't exist for `earthly/actions-setup@v1`:

```
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
