### ISSUE TITLE
rate limit exceeded

### ISSUE THREAD

**Issue by glehmann** [earthly/actions-setup#14]
with the last version, we sometime get this error:

~~~
Configured range: v0.6.29
Error: API rate limit exceeded for 65.108.86.252. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
~~~

my guess is that the action is requesting the available earthly versions (even though we specified a fixed version) and, as we are using it quite heavily, may do it too often.

As the error message suggest, a possible fix may be to authenticate when requesting github API, but I don't see anyway to pass a github token at this time.

**Comment by alexcb** [comment]
> disable the version check when using a strict version number

That's a good idea.
