### ISSUE TITLE
`github-token` is not a valid input

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/actions-setup#16]
I see this error when supplying a `github-token` as an argument to this workflow:

```
Unexpected input(s) 'github-token', valid inputs are ['version']
```

Does `github-token` need to be added to `action.yml`?
https://github.com/earthly/actions-setup/blob/0f27e887233593666346cf20e138c06085f9d18c/action.yml#L7-L10

**Comment by glehmann** [comment]
It should be fixed in #17 (which includes #15)
