### ISSUE TITLE
`version` param no longer accepts values with leading `v`

### ISSUE THREAD

**Issue by andyli** [earthly/actions-setup#20]
Previously (79c1a7ec26c371d868724182ec98d7434b18521f), I was able to use `version: "v0.7.0"`, but afedd8a45417afde5088c8225bf642c686288e25 failed:

```
Run earthly/actions-setup@v1
  with:
    version: v0.7.0
    github-token: ***
    prerelease: false
    use-cache: true
  env:
    TZ: Asia/Hong_Kong
    FORCE_COLOR: 1
    EARTHLY_STRICT: true
    EARTHLY_REMOTE_CACHE: ghcr.io/giffon/charleywong_cache:master_devcontainer_workspace
Using provided strict version v0.7.0
Install destination is /home/runner/.earthly
Matched version: vv0.7.0
earthly cache is not found
Successfully deleted pre-existing /home/runner/.earthly/bin
Error: Unexpected HTTP response: 404
```

Note that the current README suggests leading `v` is supported:
> `# or pin to an specific version, e.g. "v0.6.10"`

It's a breaking change that shouldn't happen in a 1.0.x update.

I suggest restoring leading `v` support.

**Comment by alexcb** [comment]
fixed in #21
