### ISSUE TITLE
Setup failure due to API rate limit

### ISSUE THREAD

**Issue by wingyplus** [earthly/actions-setup#22]
Hi, 

I'm the maintainer of the [earthly-emacs](https://github.com/earthly/earthly-emacs). I just change the github action to use this setup and reach the CI failure due to API rate limit. Fixed by retry until it pass. 😂 

Here is the CI log https://github.com/earthly/earthly-emacs/actions/runs/4316390768/jobs/7532107944. I also attach the archive log.

[logs_22.zip](https://github.com/earthly/actions-setup/files/10873928/logs_22.zip)

**Comment by alexcb** [comment]
#18 might be of some help: does pinning to `v0.7.1` help?

**Comment by alexcb** [comment]
rate limiting (and the github api) can be avoided by pinning to a specific version.

**Comment by drselump14** [comment]
Hi, thanks for the reply.  I can confirm that it works when pining the version to `0.7.1`.
However, I found that pinning the latest version `1.0.4` didn't work. Is there any difference with these versions?

**Comment by alexcb** [comment]
https://github.com/earthly/actions-setup/releases/tag/v1.0.5 is the latest version of `earthly/actions-setup` -- can you use that instead?

**Comment by drselump14** [comment]
I got this error when using 1.0.5 version

```Matched version: v1.0.5
earthly cache is not found
Successfully deleted pre-existing /home/runner/.earthly/bin
Error: Unexpected HTTP response: 404
```
