### ISSUE TITLE
Deprecated node12

### ISSUE THREAD

**Issue by jorsol** [earthly/actions-setup#26]
The following actions uses node12 which is deprecated and will be forced to run on node16: earthly/actions/setup-earthly@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by alexcb** [comment]
This appears to have been done in 1d702cebeea0b431f2c0c2791831657b226c9b37

is there somewhere else that we missed @jorsol ?

**Comment by jorsol** [comment]
The issue was on my side, the project was using the old `earthly/actions/setup-earthly@v1` action.
